// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var Props = require("../props.js");
var UtilsRN = require("../utilsRN.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Js_undefined = require("bs-platform/lib/js/js_undefined.js");
var ReactNative = require("react-native");

function encodeSize(size) {
  if (typeof size === "number") {
    if (size >= -9768761) {
      return "small";
    } else {
      return "large";
    }
  } else {
    return size[1];
  }
}

function make(animating, color, size, hidesWhenStopped, accessibilityLabel, accessible, hitSlop, onAccessibilityTap, onLayout, onMagicTap, responderHandlers, pointerEvents, removeClippedSubviews, style, testID, accessibilityComponentType, accessibilityLiveRegion, collapsable, importantForAccessibility, needsOffscreenAlphaCompositing, renderToHardwareTextureAndroid, accessibilityTraits, accessibilityViewIsModal, shouldRasterizeIOS) {
  var partial_arg = Props.extendView(accessibilityLabel, accessible, hitSlop, onAccessibilityTap, onLayout, onMagicTap, responderHandlers, pointerEvents, removeClippedSubviews, style, testID, accessibilityComponentType, accessibilityLiveRegion, collapsable, importantForAccessibility, needsOffscreenAlphaCompositing, renderToHardwareTextureAndroid, accessibilityTraits, accessibilityViewIsModal, shouldRasterizeIOS, {
        animating: Js_undefined.from_opt(UtilsRN.optBoolToOptJsBoolean(animating)),
        color: Js_undefined.from_opt(color),
        size: Js_undefined.from_opt(UtilsRN.option_map(encodeSize, size)),
        hidesWhenStopped: Js_undefined.from_opt(UtilsRN.optBoolToOptJsBoolean(hidesWhenStopped))
      });
  var partial_arg$1 = ReactNative.ActivityIndicator;
  return (function (param) {
      return ReasonReact.wrapJsForReason(partial_arg$1, partial_arg, param);
    });
}

exports.make = make;
/* ReasonReact Not a pure module */
