// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var TextRe = require("./textRe.js");
var ViewRe = require("./viewRe.js");
var ImageRe = require("./imageRe.js");
var AnimatedRe = require("../animatedRe.js");
var Js_boolean = require("bs-platform/lib/js/js_boolean.js");
var Js_undefined = require("bs-platform/lib/js/js_undefined.js");
var ScrollViewRe = require("./scrollViewRe.js");
var ReactNative = require("react-native");

var view = ReactNative.Animated.View;

var View = ViewRe.CreateComponent(/* module */[/* view */view]);

var view$1 = ReactNative.Animated.Image;

var Image = ImageRe.CreateComponent(/* module */[/* view */view$1]);

var view$2 = ReactNative.Animated.Text;

var Text = TextRe.CreateComponent(/* module */[/* view */view$2]);

function onScrollUpdater(x, y, $staropt$star, _) {
  var $$native = $staropt$star ? $staropt$star[0] : /* false */0;
  return AnimatedRe.$$event(/* array */[{
                nativeEvent: {
                  contentOffset: {
                    x: Js_undefined.from_opt(x),
                    y: Js_undefined.from_opt(y)
                  }
                }
              }], {
              useNativeDriver: Js_boolean.to_js_boolean($$native)
            });
}

var view$3 = ReactNative.Animated.ScrollView;

var include = ScrollViewRe.CreateComponent(/* module */[/* view */view$3]);

var scrollTo = include[0];

var scrollToEnd = include[1];

function scrollTo$1(ref) {
  return Curry._1(scrollTo, ref._component);
}

function scrollToEnd$1(ref) {
  return Curry._1(scrollToEnd, ref._component);
}

var ScrollView_003 = include[2];

var ScrollView = [
  onScrollUpdater,
  scrollTo$1,
  scrollToEnd$1,
  ScrollView_003
];

exports.View = View;
exports.Image = Image;
exports.Text = Text;
exports.ScrollView = ScrollView;
/* View Not a pure module */
