// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var UtilsRN = require("../utilsRN.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Js_undefined = require("bs-platform/lib/js/js_undefined.js");
var ReactNative = require("react-native");

function make(accessibilityLabel, color, disabled, onPress, testID, title) {
  var partial_arg = {
    accessibilityLabel: Js_undefined.from_opt(accessibilityLabel),
    color: Js_undefined.from_opt(color),
    disabled: Js_undefined.from_opt(UtilsRN.optBoolToOptJsBoolean(disabled)),
    onPress: Js_undefined.from_opt(onPress),
    testID: Js_undefined.from_opt(testID),
    title: Js_undefined.from_opt(title)
  };
  var partial_arg$1 = ReactNative.Button;
  return (function (param) {
      return ReasonReact.wrapJsForReason(partial_arg$1, partial_arg, param);
    });
}

exports.make = make;
/* ReasonReact Not a pure module */
