// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var Props = require("../props.js");
var UtilsRN = require("../utilsRN.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Js_undefined = require("bs-platform/lib/js/js_undefined.js");
var ReactNative = require("react-native");

function encodeMode(prop) {
  if (prop !== -855847923) {
    if (prop >= -281947845) {
      return "datetime";
    } else {
      return "date";
    }
  } else {
    return "time";
  }
}

function make(date, onDateChange, maximumDate, minimumDate, mode, minuteInterval, timeZoneOffsetInMinutes, accessibilityLabel, accessible, hitSlop, onAccessibilityTap, onLayout, onMagicTap, responderHandlers, pointerEvents, removeClippedSubviews, style, testID, accessibilityComponentType, accessibilityLiveRegion, collapsable, importantForAccessibility, needsOffscreenAlphaCompositing, renderToHardwareTextureAndroid, accessibilityTraits, accessibilityViewIsModal, shouldRasterizeIOS) {
  var partial_arg = Props.extendView(accessibilityLabel, accessible, hitSlop, onAccessibilityTap, onLayout, onMagicTap, responderHandlers, pointerEvents, removeClippedSubviews, style, testID, accessibilityComponentType, accessibilityLiveRegion, collapsable, importantForAccessibility, needsOffscreenAlphaCompositing, renderToHardwareTextureAndroid, accessibilityTraits, accessibilityViewIsModal, shouldRasterizeIOS, {
        date: Js_undefined.from_opt(date),
        onDateChange: Js_undefined.from_opt(onDateChange),
        maximumDate: Js_undefined.from_opt(maximumDate),
        minimumDate: Js_undefined.from_opt(minimumDate),
        mode: Js_undefined.from_opt(UtilsRN.option_map(encodeMode, mode)),
        minuteInterval: Js_undefined.from_opt(minuteInterval),
        timeZoneOffsetInMinutes: Js_undefined.from_opt(timeZoneOffsetInMinutes)
      });
  var partial_arg$1 = ReactNative.DatePickerIOS;
  return (function (param) {
      return ReasonReact.wrapJsForReason(partial_arg$1, partial_arg, param);
    });
}

exports.make = make;
/* ReasonReact Not a pure module */
