// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var UtilsRN = require("../utilsRN.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Js_undefined = require("bs-platform/lib/js/js_undefined.js");
var ReactNative = require("react-native");

function make(accessibilityLabel, behavior, testID, keyboardVerticalOffset, contentContainerStyle, style) {
  var partial_arg = {
    accessibilityLabel: Js_undefined.from_opt(accessibilityLabel),
    testID: Js_undefined.from_opt(testID),
    keyboardVerticalOffset: Js_undefined.from_opt(keyboardVerticalOffset),
    contentContainerStyle: Js_undefined.from_opt(contentContainerStyle),
    behavior: Js_undefined.from_opt(UtilsRN.option_map((function (x) {
                if (x !== -797091375) {
                  if (x >= 38537191) {
                    return "height";
                  } else {
                    return "position";
                  }
                } else {
                  return "padding";
                }
              }), behavior)),
    style: Js_undefined.from_opt(style)
  };
  var partial_arg$1 = ReactNative.KeyboardAvoidingView;
  return (function (param) {
      return ReasonReact.wrapJsForReason(partial_arg$1, partial_arg, param);
    });
}

exports.make = make;
/* ReasonReact Not a pure module */
