// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var Props = require("../props.js");
var UtilsRN = require("../utilsRN.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Js_undefined = require("bs-platform/lib/js/js_undefined.js");
var ReactNative = require("react-native");

function make(onRefresh, refreshing, colors, enabled, progressBackgroundColor, progressViewOffset, tintColor, title, titleColor, accessibilityLabel, accessible, hitSlop, onAccessibilityTap, onLayout, onMagicTap, responderHandlers, pointerEvents, removeClippedSubviews, style, testID, accessibilityComponentType, accessibilityLiveRegion, collapsable, importantForAccessibility, needsOffscreenAlphaCompositing, renderToHardwareTextureAndroid, accessibilityTraits, accessibilityViewIsModal, shouldRasterizeIOS) {
  var partial_arg = Props.extendView(accessibilityLabel, accessible, hitSlop, onAccessibilityTap, onLayout, onMagicTap, responderHandlers, pointerEvents, removeClippedSubviews, style, testID, accessibilityComponentType, accessibilityLiveRegion, collapsable, importantForAccessibility, needsOffscreenAlphaCompositing, renderToHardwareTextureAndroid, accessibilityTraits, accessibilityViewIsModal, shouldRasterizeIOS, {
        onRefresh: Js_undefined.from_opt(onRefresh),
        refreshing: Js_undefined.from_opt(UtilsRN.optBoolToOptJsBoolean(refreshing)),
        colors: Js_undefined.from_opt(colors),
        enabled: Js_undefined.from_opt(UtilsRN.optBoolToOptJsBoolean(enabled)),
        progressBackgroundColor: Js_undefined.from_opt(progressBackgroundColor),
        progressViewOffset: Js_undefined.from_opt(progressViewOffset),
        tintColor: Js_undefined.from_opt(tintColor),
        title: Js_undefined.from_opt(title),
        titleColor: Js_undefined.from_opt(titleColor)
      });
  var partial_arg$1 = ReactNative.RefreshControl;
  return (function (param) {
      return ReasonReact.wrapJsForReason(partial_arg$1, partial_arg, param);
    });
}

exports.make = make;
/* ReasonReact Not a pure module */
