// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Props = require("../props.js");
var UtilsRN = require("../utilsRN.js");
var Js_boolean = require("bs-platform/lib/js/js_boolean.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Js_undefined = require("bs-platform/lib/js/js_undefined.js");
var ReactNative = require("react-native");

function CreateComponent(Impl) {
  var scrollTo = function (ref, x, y, animated) {
    ref.scrollTo({
          x: x,
          y: y,
          animated: Js_boolean.to_js_boolean(animated)
        });
    return /* () */0;
  };
  var scrollToEnd = function (ref, animated) {
    ref.scrollToEnd({
          animated: Js_boolean.to_js_boolean(animated)
        });
    return /* () */0;
  };
  var make = function (accessibilityLabel, accessible, hitSlop, onAccessibilityTap, onLayout, onMagicTap, onScrollEndDrag, responderHandlers, pointerEvents, removeClippedSubviews, style, testID, accessibilityComponentType, accessibilityLiveRegion, collapsable, importantForAccessibility, needsOffscreenAlphaCompositing, renderToHardwareTextureAndroid, accessibilityTraits, accessibilityViewIsModal, shouldRasterizeIOS, contentContainerStyle, horizontal, keyboardDismissMode, keyboardShouldPersistTaps, onContentSizeChange, onScroll, pagingEnabled, refreshControl, scrollEnabled, showsHorizontalScrollIndicator, showsVerticalScrollIndicator, stickyHeaderIndices, overScrollMode, scrollPerfTag, alwaysBounceHorizontal, alwaysBounceVertical, automaticallyAdjustContentInsets, bounces, canCancelContentTouches, centerContent, contentInset, contentOffset, decelerationRate, directionalLockEnabled, indicatorStyle, maximumZoomScale, mimimumZoomScale, onScrollAnimationEnd, onMomentumScrollBegin, scrollEventThrottle, scrollIndicatorInsets, scrollsToTop, snapToAlignment, zoomScale) {
    var partial_arg = Props.extendView(accessibilityLabel, accessible, hitSlop, onAccessibilityTap, onLayout, onMagicTap, responderHandlers, pointerEvents, removeClippedSubviews, style, testID, accessibilityComponentType, accessibilityLiveRegion, collapsable, importantForAccessibility, needsOffscreenAlphaCompositing, renderToHardwareTextureAndroid, accessibilityTraits, accessibilityViewIsModal, shouldRasterizeIOS, {
          contentContainerStyle: Js_undefined.from_opt(contentContainerStyle),
          horizontal: Js_undefined.from_opt(UtilsRN.optBoolToOptJsBoolean(horizontal)),
          keyboardDismissMode: Js_undefined.from_opt(UtilsRN.option_map((function (x) {
                      if (x !== -453364557) {
                        if (x >= 1012481506) {
                          return "interactive";
                        } else {
                          return "none";
                        }
                      } else {
                        return "on-drag";
                      }
                    }), keyboardDismissMode)),
          keyboardShouldPersistTaps: Js_undefined.from_opt(UtilsRN.option_map((function (x) {
                      if (x !== -958984497) {
                        if (x >= 422592140) {
                          return "never";
                        } else {
                          return "handled";
                        }
                      } else {
                        return "always";
                      }
                    }), keyboardShouldPersistTaps)),
          onContentSizeChange: Js_undefined.from_opt(onContentSizeChange),
          onScroll: Js_undefined.from_opt(onScroll),
          onScrollEndDrag: Js_undefined.from_opt(onScrollEndDrag),
          onMomentumScrollBegin: Js_undefined.from_opt(onMomentumScrollBegin),
          pagingEnabled: Js_undefined.from_opt(UtilsRN.optBoolToOptJsBoolean(pagingEnabled)),
          refreshControl: Js_undefined.from_opt(refreshControl),
          scrollEnabled: Js_undefined.from_opt(UtilsRN.optBoolToOptJsBoolean(scrollEnabled)),
          showsHorizontalScrollIndicator: Js_undefined.from_opt(UtilsRN.optBoolToOptJsBoolean(showsHorizontalScrollIndicator)),
          showsVerticalScrollIndicator: Js_undefined.from_opt(UtilsRN.optBoolToOptJsBoolean(showsVerticalScrollIndicator)),
          stickyHeaderIndices: Js_undefined.from_opt(UtilsRN.option_map($$Array.of_list, stickyHeaderIndices)),
          overScrollMode: Js_undefined.from_opt(UtilsRN.option_map((function (x) {
                      if (x !== -958984497) {
                        if (x >= 422592140) {
                          return "never";
                        } else {
                          return "auto";
                        }
                      } else {
                        return "always";
                      }
                    }), overScrollMode)),
          scrollPerfTag: Js_undefined.from_opt(scrollPerfTag),
          alwaysBounceHorizontal: Js_undefined.from_opt(UtilsRN.optBoolToOptJsBoolean(alwaysBounceHorizontal)),
          alwaysBounceVertical: Js_undefined.from_opt(UtilsRN.optBoolToOptJsBoolean(alwaysBounceVertical)),
          automaticallyAdjustContentInsets: Js_undefined.from_opt(UtilsRN.optBoolToOptJsBoolean(automaticallyAdjustContentInsets)),
          bounces: Js_undefined.from_opt(UtilsRN.optBoolToOptJsBoolean(bounces)),
          canCancelContentTouches: Js_undefined.from_opt(UtilsRN.optBoolToOptJsBoolean(canCancelContentTouches)),
          centerContent: Js_undefined.from_opt(UtilsRN.optBoolToOptJsBoolean(centerContent)),
          contentInset: Js_undefined.from_opt(contentInset),
          contentOffset: Js_undefined.from_opt(UtilsRN.option_map((function (param) {
                      return {
                              x: param[/* x */0],
                              y: param[/* y */1]
                            };
                    }), contentOffset)),
          decelerationRate: Js_undefined.from_opt(UtilsRN.option_map((function (x) {
                      if (x >= 812216871) {
                        return "normal";
                      } else {
                        return "fast";
                      }
                    }), decelerationRate)),
          directionalLockEnabled: Js_undefined.from_opt(UtilsRN.optBoolToOptJsBoolean(directionalLockEnabled)),
          indicatorStyle: Js_undefined.from_opt(UtilsRN.option_map((function (x) {
                      if (x !== 465819841) {
                        if (x >= 888264127) {
                          return "black";
                        } else {
                          return "white";
                        }
                      } else {
                        return "default";
                      }
                    }), indicatorStyle)),
          maximumZoomScale: Js_undefined.from_opt(maximumZoomScale),
          mimimumZoomScale: Js_undefined.from_opt(mimimumZoomScale),
          onScrollAnimationEnd: Js_undefined.from_opt(onScrollAnimationEnd),
          scrollEventThrottle: Js_undefined.from_opt(scrollEventThrottle),
          scrollIndicatorInsets: Js_undefined.from_opt(scrollIndicatorInsets),
          scrollsToTop: Js_undefined.from_opt(UtilsRN.optBoolToOptJsBoolean(scrollsToTop)),
          snapToAlignment: Js_undefined.from_opt(UtilsRN.option_map((function (x) {
                      if (x !== 67859554) {
                        if (x >= 98248149) {
                          return "center";
                        } else {
                          return "end";
                        }
                      } else {
                        return "start";
                      }
                    }), snapToAlignment)),
          zoomScale: Js_undefined.from_opt(zoomScale)
        });
    var partial_arg$1 = Impl[/* view */0];
    return (function (param) {
        return ReasonReact.wrapJsForReason(partial_arg$1, partial_arg, param);
      });
  };
  return /* module */[
          /* scrollTo */scrollTo,
          /* scrollToEnd */scrollToEnd,
          /* make */make
        ];
}

var Impl = /* module */[/* ScrollView */ReactNative.ScrollView];

function scrollTo(ref, x, y, animated) {
  ref.scrollTo({
        x: x,
        y: y,
        animated: Js_boolean.to_js_boolean(animated)
      });
  return /* () */0;
}

function scrollToEnd(ref, animated) {
  ref.scrollToEnd({
        animated: Js_boolean.to_js_boolean(animated)
      });
  return /* () */0;
}

function make(accessibilityLabel, accessible, hitSlop, onAccessibilityTap, onLayout, onMagicTap, onScrollEndDrag, responderHandlers, pointerEvents, removeClippedSubviews, style, testID, accessibilityComponentType, accessibilityLiveRegion, collapsable, importantForAccessibility, needsOffscreenAlphaCompositing, renderToHardwareTextureAndroid, accessibilityTraits, accessibilityViewIsModal, shouldRasterizeIOS, contentContainerStyle, horizontal, keyboardDismissMode, keyboardShouldPersistTaps, onContentSizeChange, onScroll, pagingEnabled, refreshControl, scrollEnabled, showsHorizontalScrollIndicator, showsVerticalScrollIndicator, stickyHeaderIndices, overScrollMode, scrollPerfTag, alwaysBounceHorizontal, alwaysBounceVertical, automaticallyAdjustContentInsets, bounces, canCancelContentTouches, centerContent, contentInset, contentOffset, decelerationRate, directionalLockEnabled, indicatorStyle, maximumZoomScale, mimimumZoomScale, onScrollAnimationEnd, onMomentumScrollBegin, scrollEventThrottle, scrollIndicatorInsets, scrollsToTop, snapToAlignment, zoomScale) {
  var partial_arg = Props.extendView(accessibilityLabel, accessible, hitSlop, onAccessibilityTap, onLayout, onMagicTap, responderHandlers, pointerEvents, removeClippedSubviews, style, testID, accessibilityComponentType, accessibilityLiveRegion, collapsable, importantForAccessibility, needsOffscreenAlphaCompositing, renderToHardwareTextureAndroid, accessibilityTraits, accessibilityViewIsModal, shouldRasterizeIOS, {
        contentContainerStyle: Js_undefined.from_opt(contentContainerStyle),
        horizontal: Js_undefined.from_opt(UtilsRN.optBoolToOptJsBoolean(horizontal)),
        keyboardDismissMode: Js_undefined.from_opt(UtilsRN.option_map((function (x) {
                    if (x !== -453364557) {
                      if (x >= 1012481506) {
                        return "interactive";
                      } else {
                        return "none";
                      }
                    } else {
                      return "on-drag";
                    }
                  }), keyboardDismissMode)),
        keyboardShouldPersistTaps: Js_undefined.from_opt(UtilsRN.option_map((function (x) {
                    if (x !== -958984497) {
                      if (x >= 422592140) {
                        return "never";
                      } else {
                        return "handled";
                      }
                    } else {
                      return "always";
                    }
                  }), keyboardShouldPersistTaps)),
        onContentSizeChange: Js_undefined.from_opt(onContentSizeChange),
        onScroll: Js_undefined.from_opt(onScroll),
        onScrollEndDrag: Js_undefined.from_opt(onScrollEndDrag),
        onMomentumScrollBegin: Js_undefined.from_opt(onMomentumScrollBegin),
        pagingEnabled: Js_undefined.from_opt(UtilsRN.optBoolToOptJsBoolean(pagingEnabled)),
        refreshControl: Js_undefined.from_opt(refreshControl),
        scrollEnabled: Js_undefined.from_opt(UtilsRN.optBoolToOptJsBoolean(scrollEnabled)),
        showsHorizontalScrollIndicator: Js_undefined.from_opt(UtilsRN.optBoolToOptJsBoolean(showsHorizontalScrollIndicator)),
        showsVerticalScrollIndicator: Js_undefined.from_opt(UtilsRN.optBoolToOptJsBoolean(showsVerticalScrollIndicator)),
        stickyHeaderIndices: Js_undefined.from_opt(UtilsRN.option_map($$Array.of_list, stickyHeaderIndices)),
        overScrollMode: Js_undefined.from_opt(UtilsRN.option_map((function (x) {
                    if (x !== -958984497) {
                      if (x >= 422592140) {
                        return "never";
                      } else {
                        return "auto";
                      }
                    } else {
                      return "always";
                    }
                  }), overScrollMode)),
        scrollPerfTag: Js_undefined.from_opt(scrollPerfTag),
        alwaysBounceHorizontal: Js_undefined.from_opt(UtilsRN.optBoolToOptJsBoolean(alwaysBounceHorizontal)),
        alwaysBounceVertical: Js_undefined.from_opt(UtilsRN.optBoolToOptJsBoolean(alwaysBounceVertical)),
        automaticallyAdjustContentInsets: Js_undefined.from_opt(UtilsRN.optBoolToOptJsBoolean(automaticallyAdjustContentInsets)),
        bounces: Js_undefined.from_opt(UtilsRN.optBoolToOptJsBoolean(bounces)),
        canCancelContentTouches: Js_undefined.from_opt(UtilsRN.optBoolToOptJsBoolean(canCancelContentTouches)),
        centerContent: Js_undefined.from_opt(UtilsRN.optBoolToOptJsBoolean(centerContent)),
        contentInset: Js_undefined.from_opt(contentInset),
        contentOffset: Js_undefined.from_opt(UtilsRN.option_map((function (param) {
                    return {
                            x: param[/* x */0],
                            y: param[/* y */1]
                          };
                  }), contentOffset)),
        decelerationRate: Js_undefined.from_opt(UtilsRN.option_map((function (x) {
                    if (x >= 812216871) {
                      return "normal";
                    } else {
                      return "fast";
                    }
                  }), decelerationRate)),
        directionalLockEnabled: Js_undefined.from_opt(UtilsRN.optBoolToOptJsBoolean(directionalLockEnabled)),
        indicatorStyle: Js_undefined.from_opt(UtilsRN.option_map((function (x) {
                    if (x !== 465819841) {
                      if (x >= 888264127) {
                        return "black";
                      } else {
                        return "white";
                      }
                    } else {
                      return "default";
                    }
                  }), indicatorStyle)),
        maximumZoomScale: Js_undefined.from_opt(maximumZoomScale),
        mimimumZoomScale: Js_undefined.from_opt(mimimumZoomScale),
        onScrollAnimationEnd: Js_undefined.from_opt(onScrollAnimationEnd),
        scrollEventThrottle: Js_undefined.from_opt(scrollEventThrottle),
        scrollIndicatorInsets: Js_undefined.from_opt(scrollIndicatorInsets),
        scrollsToTop: Js_undefined.from_opt(UtilsRN.optBoolToOptJsBoolean(scrollsToTop)),
        snapToAlignment: Js_undefined.from_opt(UtilsRN.option_map((function (x) {
                    if (x !== 67859554) {
                      if (x >= 98248149) {
                        return "center";
                      } else {
                        return "end";
                      }
                    } else {
                      return "start";
                    }
                  }), snapToAlignment)),
        zoomScale: Js_undefined.from_opt(zoomScale)
      });
  var partial_arg$1 = Impl[/* view */0];
  return (function (param) {
      return ReasonReact.wrapJsForReason(partial_arg$1, partial_arg, param);
    });
}

var ScrollView = /* module */[
  /* scrollTo */scrollTo,
  /* scrollToEnd */scrollToEnd,
  /* make */make
];

exports.CreateComponent = CreateComponent;
exports.ScrollView = ScrollView;
/* Impl Not a pure module */
