// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var UtilsRN = require("../utilsRN.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Js_undefined = require("bs-platform/lib/js/js_undefined.js");
var ReactNative = require("react-native");

function CreateComponent(Impl) {
  var make = function (accessible, allowFontScaling, ellipsizeMode, numberOfLines, onLayout, onLongPress, onPress, pressRetentionOffset, selectable, style, testID, selectionColor, textBreakStrategy, adjustsFontSizeToFit, minimumFontScale, suppressHighlighting, value, children) {
    return ReasonReact.wrapJsForReason(Impl[/* view */0], {
                accessible: Js_undefined.from_opt(UtilsRN.optBoolToOptJsBoolean(accessible)),
                allowFontScaling: Js_undefined.from_opt(UtilsRN.optBoolToOptJsBoolean(allowFontScaling)),
                ellipsizeMode: Js_undefined.from_opt(UtilsRN.option_map((function (param) {
                            if (param >= -866200747) {
                              if (param >= -856246640) {
                                return "tail";
                              } else {
                                return "middle";
                              }
                            } else if (param >= -989124320) {
                              return "head";
                            } else {
                              return "clip";
                            }
                          }), ellipsizeMode)),
                numberOfLines: Js_undefined.from_opt(numberOfLines),
                onLayout: Js_undefined.from_opt(onLayout),
                onLongPress: Js_undefined.from_opt(onLongPress),
                onPress: Js_undefined.from_opt(onPress),
                pressRetentionOffset: Js_undefined.from_opt(pressRetentionOffset),
                selectable: Js_undefined.from_opt(UtilsRN.optBoolToOptJsBoolean(selectable)),
                style: Js_undefined.from_opt(style),
                testID: Js_undefined.from_opt(testID),
                selectionColor: Js_undefined.from_opt(selectionColor),
                textBreakStrategy: Js_undefined.from_opt(UtilsRN.option_map((function (param) {
                            if (param !== -128197688) {
                              if (param >= 947848242) {
                                return "simple";
                              } else {
                                return "highQuality";
                              }
                            } else {
                              return "balanced";
                            }
                          }), textBreakStrategy)),
                adjustsFontSizeToFit: Js_undefined.from_opt(UtilsRN.optBoolToOptJsBoolean(adjustsFontSizeToFit)),
                minimumFontScale: Js_undefined.from_opt(minimumFontScale),
                suppressHighlighting: Js_undefined.from_opt(UtilsRN.optBoolToOptJsBoolean(suppressHighlighting))
              }, value ? $$Array.append(/* array */[value[0]], children) : children);
  };
  return /* module */[/* make */make];
}

var Impl = /* module */[/* Text */ReactNative.Text];

function make(accessible, allowFontScaling, ellipsizeMode, numberOfLines, onLayout, onLongPress, onPress, pressRetentionOffset, selectable, style, testID, selectionColor, textBreakStrategy, adjustsFontSizeToFit, minimumFontScale, suppressHighlighting, value, children) {
  return ReasonReact.wrapJsForReason(Impl[/* view */0], {
              accessible: Js_undefined.from_opt(UtilsRN.optBoolToOptJsBoolean(accessible)),
              allowFontScaling: Js_undefined.from_opt(UtilsRN.optBoolToOptJsBoolean(allowFontScaling)),
              ellipsizeMode: Js_undefined.from_opt(UtilsRN.option_map((function (param) {
                          if (param >= -866200747) {
                            if (param >= -856246640) {
                              return "tail";
                            } else {
                              return "middle";
                            }
                          } else if (param >= -989124320) {
                            return "head";
                          } else {
                            return "clip";
                          }
                        }), ellipsizeMode)),
              numberOfLines: Js_undefined.from_opt(numberOfLines),
              onLayout: Js_undefined.from_opt(onLayout),
              onLongPress: Js_undefined.from_opt(onLongPress),
              onPress: Js_undefined.from_opt(onPress),
              pressRetentionOffset: Js_undefined.from_opt(pressRetentionOffset),
              selectable: Js_undefined.from_opt(UtilsRN.optBoolToOptJsBoolean(selectable)),
              style: Js_undefined.from_opt(style),
              testID: Js_undefined.from_opt(testID),
              selectionColor: Js_undefined.from_opt(selectionColor),
              textBreakStrategy: Js_undefined.from_opt(UtilsRN.option_map((function (param) {
                          if (param !== -128197688) {
                            if (param >= 947848242) {
                              return "simple";
                            } else {
                              return "highQuality";
                            }
                          } else {
                            return "balanced";
                          }
                        }), textBreakStrategy)),
              adjustsFontSizeToFit: Js_undefined.from_opt(UtilsRN.optBoolToOptJsBoolean(adjustsFontSizeToFit)),
              minimumFontScale: Js_undefined.from_opt(minimumFontScale),
              suppressHighlighting: Js_undefined.from_opt(UtilsRN.optBoolToOptJsBoolean(suppressHighlighting))
            }, value ? $$Array.append(/* array */[value[0]], children) : children);
}

var Text = /* module */[/* make */make];

exports.CreateComponent = CreateComponent;
exports.Text = Text;
/* Impl Not a pure module */
