// Generated by BUCKLESCRIPT VERSION 2.1.1, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/src/ReasonReact.js");
var ReactNative = require("react-native");

function make(data, renderItem, _children) {
  return ReasonReact.wrapJsForReason(ReactNative.VirtualizedList.virtualizedList, {
              data: data,
              renderItem: renderItem
            }, _children);
}

exports.make = make;
/* ReasonReact Not a pure module */
