// Generated by BUCKLESCRIPT VERSION 2.1.1, PLEASE EDIT WITH CARE
'use strict';

var Js_mapperRt       = require("bs-platform/lib/js/js_mapperRt.js");
var ReactNative       = require("react-native");
var Js_null_undefined = require("bs-platform/lib/js/js_null_undefined.js");

var jsMapperConstantArray = /* array */[
  /* tuple */[
    -690730680,
    "SavedPhotos"
  ],
  /* tuple */[
    3256577,
    "All"
  ],
  /* tuple */[
    150091770,
    "Event"
  ],
  /* tuple */[
    213995227,
    "Library"
  ],
  /* tuple */[
    242599190,
    "Faces"
  ],
  /* tuple */[
    316308146,
    "PhotoStream"
  ],
  /* tuple */[
    884572943,
    "Album"
  ]
];

var jsMapperConstantArray$1 = /* array */[
  /* tuple */[
    3256577,
    "All"
  ],
  /* tuple */[
    438979512,
    "Videos"
  ],
  /* tuple */[
    670058401,
    "Photos"
  ]
];

function getPhotos(first, after, $staropt$star, groupName, $staropt$star$1, mimeTypes, _) {
  var groupTypes = $staropt$star ? $staropt$star[0] : /* SavedPhotos */-690730680;
  var assetType = $staropt$star$1 ? $staropt$star$1[0] : /* Photos */670058401;
  return ReactNative.CameraRoll.getPhotos({
              first: first,
              after: Js_null_undefined.from_opt(after),
              groupTypes: Js_mapperRt.binSearch(7, groupTypes, jsMapperConstantArray),
              groupName: Js_null_undefined.from_opt(groupName),
              assetType: Js_mapperRt.binSearch(3, assetType, jsMapperConstantArray$1),
              mimeTypes: Js_null_undefined.from_opt(mimeTypes)
            });
}

function hasNextPage(cursor) {
  return +cursor.has_next_page;
}

exports.hasNextPage = hasNextPage;
exports.getPhotos   = getPhotos;
/* react-native Not a pure module */
