// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var ReactNative = require("react-native");

function dismiss() {
  ReactNative.Keyboard.dismiss();
  return /* () */0;
}

exports.dismiss = dismiss;
/* react-native Not a pure module */
