// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var ViewRe = require("./components/viewRe.js");
var AnimatedRe = require("./animatedRe.js");
var PanResponderRe = require("./panResponderRe.js");
var ResponderUtils = require("./responderUtils.js");
var PanResponderUtils = require("./PanResponderUtils.js");

var View_000 = /* make */ViewRe.View[0];

var View = /* module */[
  View_000,
  /* responderHandlers */ResponderUtils.responderHandlers
];

var Animated = /* module */[
  /* Animation */AnimatedRe.Animation,
  /* CompositeAnimation */AnimatedRe.CompositeAnimation,
  /* Interpolation */AnimatedRe.Interpolation,
  /* Value */AnimatedRe.Value,
  /* ValueXY */AnimatedRe.ValueXY,
  /* event */AnimatedRe.$$event,
  /* delay */AnimatedRe.delay,
  /* sequence */AnimatedRe.sequence,
  /* parallel */AnimatedRe.parallel,
  /* stagger */AnimatedRe.stagger,
  /* loop */AnimatedRe.loop,
  /* Timing */AnimatedRe.Timing,
  /* TimingXY */AnimatedRe.TimingXY,
  /* Spring */AnimatedRe.Spring,
  /* SpringXY */AnimatedRe.SpringXY,
  /* Decay */AnimatedRe.Decay,
  /* DecayXY */AnimatedRe.DecayXY,
  /* Text */0,
  /* ScrollView */0,
  /* View */0,
  /* Image */0
];

var PanResponder = /* module */[
  /* callback */PanResponderRe.callback,
  /* create */PanResponderRe.create,
  /* panHandlers */PanResponderUtils.panHandlers
];

var ActivityIndicator = 0;

var Button = 0;

var DatePickerIOS = 0;

var FlatList = 0;

var Modal = 0;

var Picker = 0;

var RefreshControl = 0;

var ScrollView = 0;

var SectionList = 0;

var Slider = 0;

var StatusBar = 0;

var Switch = 0;

var TabBarIOS = 0;

var Text = 0;

var TextInput = 0;

var TouchableHighlight = 0;

var TouchableOpacity = 0;

var TouchableWithoutFeedback = 0;

var WebView = 0;

var Image = 0;

var ImageBackground = 0;

var Alert = 0;

var AlertIOS = 0;

var AppRegistry = 0;

var AppState = 0;

var AsyncStorage = 0;

var BackHandler = 0;

var Dimensions = 0;

var Linking = 0;

var NativeModules = 0;

var NativeEventEmitter = 0;

var Platform = 0;

var PixelRatio = 0;

var StyleSheet = 0;

var Vibration = 0;

var SegmentedControllOS = 0;

var Packager = 0;

var Style = 0;

exports.ActivityIndicator = ActivityIndicator;
exports.Button = Button;
exports.DatePickerIOS = DatePickerIOS;
exports.FlatList = FlatList;
exports.Modal = Modal;
exports.Picker = Picker;
exports.RefreshControl = RefreshControl;
exports.ScrollView = ScrollView;
exports.SectionList = SectionList;
exports.Slider = Slider;
exports.StatusBar = StatusBar;
exports.Switch = Switch;
exports.TabBarIOS = TabBarIOS;
exports.Text = Text;
exports.TextInput = TextInput;
exports.TouchableHighlight = TouchableHighlight;
exports.TouchableOpacity = TouchableOpacity;
exports.TouchableWithoutFeedback = TouchableWithoutFeedback;
exports.WebView = WebView;
exports.View = View;
exports.Image = Image;
exports.ImageBackground = ImageBackground;
exports.Animated = Animated;
exports.Alert = Alert;
exports.AlertIOS = AlertIOS;
exports.AppRegistry = AppRegistry;
exports.AppState = AppState;
exports.AsyncStorage = AsyncStorage;
exports.BackHandler = BackHandler;
exports.Dimensions = Dimensions;
exports.Linking = Linking;
exports.NativeModules = NativeModules;
exports.NativeEventEmitter = NativeEventEmitter;
exports.Platform = Platform;
exports.PixelRatio = PixelRatio;
exports.StyleSheet = StyleSheet;
exports.PanResponder = PanResponder;
exports.Vibration = Vibration;
exports.SegmentedControllOS = SegmentedControllOS;
exports.Packager = Packager;
exports.Style = Style;
/* ViewRe Not a pure module */
